/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace MainScene_UI
{
    partial class AgreementWindow : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static AgreementWindow Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btClose = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text txTitle = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btOk = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btCancel = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text txVersion = default;
        [AutoGenerated, SerializeField, HideInInspector] TMPro.TextMeshProUGUI text = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btClose);
            SubscribeOnChanged(txTitle);
            SubscribeOnChanged(btOk);
            SubscribeOnChanged(btCancel);
            SubscribeOnChanged(txVersion);
            SubscribeOnChanged(text);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}