/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace MainScene_UI
{
    partial class SetingsWindow : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static SetingsWindow Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btClose = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text txTitle = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btOk = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btCancel = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifPath = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx1 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifLibraryPath = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx2 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifProjectFile = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx3 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifOutputGraphicsFolder = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx5 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifInputMetaFileName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx4 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifOutputMetaFileName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx6 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx7 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifPathsMetaFileName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifRunMetaFileName = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx8 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifConsoleMaxLines = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx9 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifConsolefontSize = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Text tx10 = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.InputField ifMaxGraphicFilesCount = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(btClose);
            SubscribeOnChanged(txTitle);
            SubscribeOnChanged(btOk);
            SubscribeOnChanged(btCancel);
            SubscribeOnChanged(tx);
            SubscribeOnChanged(ifPath);
            SubscribeOnChanged(tx1);
            SubscribeOnChanged(ifLibraryPath);
            SubscribeOnChanged(tx2);
            SubscribeOnChanged(ifProjectFile);
            SubscribeOnChanged(tx3);
            SubscribeOnChanged(ifOutputGraphicsFolder);
            SubscribeOnChanged(tx5);
            SubscribeOnChanged(ifInputMetaFileName);
            SubscribeOnChanged(tx4);
            SubscribeOnChanged(ifOutputMetaFileName);
            SubscribeOnChanged(tx6);
            SubscribeOnChanged(tx7);
            SubscribeOnChanged(ifPathsMetaFileName);
            SubscribeOnChanged(ifRunMetaFileName);
            SubscribeOnChanged(tx8);
            SubscribeOnChanged(ifConsoleMaxLines);
            SubscribeOnChanged(tx9);
            SubscribeOnChanged(ifConsolefontSize);
            SubscribeOnChanged(tx10);
            SubscribeOnChanged(ifMaxGraphicFilesCount);
            Subscribe(btClose, () => this.Close());
            Subscribe(btCancel, () => this.Close());
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}