/////////////////////////////////////////
//     THIS IS AUTOGENERATED CODE      //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using CometUI;

namespace GraphicsScene_UI
{
    partial class GraphicsPanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static GraphicsPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        //[Header("Controls (auto capture)")]
        [Header("Custom")]
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Image im = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btPrev = default;
        [AutoGenerated, SerializeField, HideInInspector] UnityEngine.UI.Button btNext = default;
        #pragma warning restore 0414
        
        public override void AutoSubscribe()
        {
            SubscribeOnChanged(im);
            SubscribeOnChanged(btPrev);
            SubscribeOnChanged(btNext);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}